config/routes.rb
Test::Application.routes.draw do

   resources :blog_entries do
     resources :comments, :only => [:create, :destroy]
   end

   resources :users, :only => [ :new,:create ]
   resources :sessions, :only => [:new, :create, :destroy]

   root :to => 'blog_entries#index'

end

app/models/blog_entry.rb
class BlogEntry < ActiveRecord::Base
  has_many :comments 

  attr_accessible :body, :title, :mashify_title, :dashify_title

  validates :body, :presence => true
  validates :title, :presence => true

  def dashify(str)
    str = str.to_s.upcase.gsub('-','').strip.chars.join('-')
    return str
  end
  
  def mashify(str)
    str = str.to_s.upcase.gsub('*', '').strip.chars.join('*').to_s
    return str
  end

  def formatted_title
    str = self.title

    if( self.mashify_title? )
      str = self.mashify(str)
    end
    if( self.dashify_title? )
      str = self.dashify(str)
    end
    return str
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :blog_entry
  attr_accessible :body, :commenter

end

app/models/user.rb
require "bcrypt"

class User < ActiveRecord::Base
  include BCrypt

  attr_accessible :login, :password
  validates :login, presence: true
  validates :password_digest, presence: true

  def password=(str)
    if str.present?
      self.password_digest = Password.create(str).to_s
    end
  end

  def password
    if(password_digest != nil)
      @password ||= Password.new(self.password_digest)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  before_filter :authorize
  helper_method :current_user, :logged_in?

protected

  def authorize
    current_user
  end

  def current_user
    if session[:user_id]
      @current_user ||= User.find_by_id session[:user_id]
    end
  end

  def logged_in?
    current_user.present?
  end

end

app/controllers/blog_entries_controller.rb
class BlogEntriesController < ApplicationController
  before_filter :require_blog_entry, :only => [:show, :update, :edit, :destroy]
  
  def index
   @blog_all = BlogEntry.all
  end

  def show
  end

  def new
    @blog_entry = BlogEntry.new
  end

  def create
    @blog_entry = BlogEntry.new(params[:blog_entry])
    @blog_entry.save!
    redirect_to blog_entry_path @blog_entry.id
  end

  def destroy
    @blog_entry.destroy
    redirect_to blog_entries_path
  end
 
 def edit
 end

 def update
    @blog_entry.update_attributes(blog_entry_params)
    
    redirect_to blog_entry_path(id: @blog_entry.id)
 end

protected
  def require_blog_entry
    unless @blog_entry = BlogEntry.find_by_id(params[:id])
      render :inline => 'Not found', :status => 404 and return false
    end
  end

  def blog_entry_params
    params.require(:blog_entry).permit(:title, :body, :mashify_title, :dashify_title)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    def index
      @post ||= BlogEntry.all
    end

    def create
       @blog_entry = BlogEntry.find_by_id(params[:blog_entry_id]) 
       @blog_entry.comments.create(params[:comment].permit(:commenter, :body))

       redirect_to blog_entry_path(@blog_entry)
    end

    def show
      @post = BlogEntry.find_by_id(params[:post_id])
    end

    def update
    end

    def destroy
      @blog_entry = BlogEntry.find_by_id(params[:blog_entry_id])
      @comment    = @blog_entry.comments.find_by_id(params[:id])
      @comment.destroy

      redirect_to blog_entry_path(@blog_entry)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def index
  end

  def new
  end

  def create
    @temp_pass = params[:password]
    @user = User.find_by_login params[:login]

    if @user.present?
      if @user.password == @temp_pass 
        session[:user_id] = @user.id
      end
    end

    redirect_to root_path
  end

  def destroy
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end

  def new
    @user = User.new(params[:user])
  end

  def create  
    @user = User.new(params[:user])
  
    unless @user.save
      render :action => :new and return
      @users = User.all
    else
      @users = User.all
      redirect_to root_path
    end

  end

protected
  def user_require
    params.require(:user).permit(:login, :password_digest)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/blog_entries/edit.html.erb
<div class="row-fluid">
  <div class="span6">
      <%= form_for @blog_entry, :html => {:class => 'form-horizontal'} do |f| %>
      <legend class="blue-wrap" id="align"> Edit A Blog! </legend>
        <div class="control-group"> 
          <%= f.label :title, :class => 'control-label' %>
          <div class="controls">   
            <%= f.text_field :title, :placeholder => 'title', :class => 'span10' %>
          </div>
        </div>
        <div class="control-group">
          <%= f.label :body, :class => 'control-label' %>
          <div class="controls">
              <%= f.text_area :body, rows: '5', placeholder: 'body',class: 'span10' %>
          </div>
        </div>
        <div class="control-group">
          <div class="controls">
            <%= f.label :dashify_title, :class => 'checkbox' do %>
              <%= f.check_box :dashify_title %>
              Dashify title
            <% end %>
          </div>
        </div>
        <div class="control-group">
          <div class="controls">
            <%= f.label :mashify_title, :class => 'checkbox' do %>
              <%= f.check_box :mashify_title %>
              Mashify title
            <% end %>
          </div>
        </div>
        <div class="form-actions">
          <%= f.submit 'Save', class: "btn btn-default btn-primary" %>
        </div>
      <% end %>
  </div>
</div>

app/views/blog_entries/index.html.erb
<div class="row centers">
  <div class="span12 centers">
    <legend class="blue-wrap" id="align"><strong>Blog Entries</strong></legend>
    <span>
        <ul class="nav nav-pills offset1">
          <% @blog_all.each do |f| %>
            <li class="span3" id="align">
              <a href= <%= blog_entry_path f.id %> ><h4><%= f.title %></h4></a>
            </li>
          <% end %>
        </ul>
    </span>
  </div>
</div>

app/views/blog_entries/new.html.erb
<div class="row-fluid">
  <div class="span6">
      <%= form_for @blog_entry, :html => {:class => 'form-horizontal'} do |f| %>
      <legend class="blue-wrap" id="align"> Create A New Blog! </legend>
        <div class="control-group"> 
          <%= f.label :title, :class => 'control-label' %>
          <div class="controls">   
            <%= f.text_field :title, :placeholder => 'title', :class => 'span10' %>
          </div>
        </div>
        <div class="control-group">
          <%= f.label :body, :class => 'control-label' %>
          <div class="controls">
              <%= f.text_area :body, rows: '5', placeholder: 'body',class: 'span10' %>
          </div>
        </div>
        <div class="form-actions">
          <%= f.submit 'Save', class: "btn btn-default btn-primary" %>
        </div>
      <% end %>
  </div>
</div>

app/views/blog_entries/show.html.erb
<div class="hero-unit row-fluid">
  <span class="span3 wrapping">
    <h2><%= @blog_entry.formatted_title %></h2>
      <div class="row-fluid">
        <%= button_to 'Delete-User', @del_entry, :method => :delete, data: { confirm: 'Are you sure?'}, class: "btn btn-mini btn-default" %>
        <%= form_for ([@blog_entry, @blog_entry.comments.build]) do |f| %>
          <p>
            <%= f.label :commenter %>
            <%= f.text_field :commenter %>
          </p>

          <p>
            <%= f.label :body %> 
            <%= f.text_field :body %>
            <%= f.submit 'Submit', class: "btn btn-default btn-primary" %>
          </p>
          <p><%= link_to "Back", new_blog_entry_path %></p>
        <% end %>
      </div>
  </span>

  <span class="hero-unit span6 wrapping" id="child-hero">
    <div class="hero-unit wrapping">
      <p class="blue-wrap"><%= @blog_entry.body %></p>
    </div>
    <span class="pull-right">
      <%= link_to "Edit", edit_blog_entry_path( @blog_entry ) %>
    </span>
    <legend>
      <h3 class="blue-wrap">Comments</h3>
    </legend>
    <span class="label label-info pull-right"><%= @blog_entry.comments.count %> Comments</span>
    <% @blog_entry.comments.reload.each do |x| %>
      <h4><%= x.body %></h4>
      <p class="blue-wrap">@<%= x.commenter %><%= link_to "Delete", blog_entry_comment_path(:blog_entry_id => @blog_entry.id, :id => x.id), :method => :delete, class: "btn btn-default btn-small pull-right" %></p>
    <% end %>
  </span>
</div>

app/views/home/index.html.erb
<div class="row centers">
  <div class="span12 centers">
    <legend class="blue-wrap" id="align"><strong>All Current Bloggers</strong></legend>
    <span>
        <ul class="nav nav-pills offset1">
          <% @blog_all.each do |f| %>
            <li class="span3" id="align">
             <a href=<%= f.id %> ><h4><%= f.title %></h4></a>
            </li>
      	  <% end %>
        </ul>
    </span>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Test</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>

<body style="background:lightgray">

  <div class="navbar navbar-inverse navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container">
        <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to 'Blog', root_path, :class => 'brand' %>
        <div class="nav-collapse collapse">
            <ul class="nav">
              <%= content_tag 'li', link_to('Home', root_path), :class => "#{'active' if request.path == root_path}" %>
              <%= content_tag 'li', link_to('New Blog Entry', new_blog_entry_path), :class => "#{'active' if request.path == new_blog_entry_path}" %>
              <%= content_tag 'li', link_to('Create new user' , new_user_path), :class => "#{'active' if request.path == new_user_path}" %>
              <% if current_user %>
              <%= content_tag 'li', link_to('Logout' , new_session_path), :class => "#{'active' if request.path == new_session_path}" %>
              <% else %>
              <%= content_tag 'li', link_to('Login' , new_session_path), :class => "#{'active' if request.path == new_session_path}" %>
              <% end %>
            </ul>
        </div>
      </div>
    </div>
  </div>
    
  <div class="container" id="content">
    <%= yield %>
  </div> 
</body>
</html>

app/views/users/create.html.erb
<div class="row centers">
  <div class="span12 centers">
    <legend class="blue-wrap" id="align"><strong>All Bloggers</strong></legend>
        <ul class="nav nav-pills offset1">
          <% @users.each do |f| %>
          <li class="span3" id="align">
            <a href= <%= root_path %> ><h4><%= f.login %></h4></a>
          </li>
          <% end %>
        </ul>
  </div>
</div>

app/views/users/new.html.erb
<div class="row-fluid">
  <div class="span6">
    <% if @user.errors.present? %>
      <p class="text-error">Please check all fields carefully</p>
    <% end %>
    <%= form_for @user, html: {class: 'form-horizontal'} do |f| %>
    <legend class="blue-wrap" id="align"> Create a new account </legend>
    <div class="control-group">
      <%= f.label :login, class: "control-label" %>
      <div class="controls">
        <%= f.text_field :login, placeholder: 'title', class: "span6" %>
      </div>
    </div>
    <div class="control-group">
      <%= f.label :password, class: "control-label" %>
      <div class="controls">
        <%= f.text_field :password, placeholder: 'Password...', class: "input-small, span6", type: "password" %>
      </div>
    </div>
    <div class="form-actions">
      <%= f.submit 'Submit', class: "btn, btn-default, btn-primary" %>
    </div>
    <% end %>
  </div>
</div>